import React, { useState } from 'react';
import {
  View, Text, TouchableOpacity, ScrollView, StyleSheet, SafeAreaView,
} from 'react-native';
import UrgencyBanner from '../components/UrgencyBanner';
import ConfidenceBar from '../components/ConfidenceBar';
import { COLORS } from '../constants/colors';

export default function ResultScreen({ navigation, route }) {
  const result = route.params?.result || {};
  const {
    urgency_tier,
    confidence_score,
    explanation,
    breed_risk_note,
    module_outputs = {},
    triage_id,
  } = result;

  const [expanded, setExpanded] = useState(false);
  const showMonitorCta = urgency_tier === 'MONITOR' || urgency_tier === 'SAFE';

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.container}>
        <UrgencyBanner urgencyTier={urgency_tier} />

        <ConfidenceBar score={confidence_score} />

        <View style={styles.card}>
          <Text style={styles.cardTitle}>What our Artificial Intelligence (AI) found</Text>
          <Text style={styles.cardBody}>{explanation || 'No explanation available.'}</Text>
        </View>

        {breed_risk_note ? (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Breed note</Text>
            <Text style={styles.cardBody}>{breed_risk_note}</Text>
          </View>
        ) : null}

        <TouchableOpacity
          style={styles.btnPrimary}
          onPress={() => navigation.navigate('VetBooking', { triageId: triage_id })}
          accessibilityLabel="Book a vet now"
          accessibilityRole="button"
        >
          <Text style={styles.btnPrimaryText}>Book a vet now</Text>
        </TouchableOpacity>

        {showMonitorCta && (
          <TouchableOpacity
            style={styles.btnSecondary}
            onPress={() => navigation.navigate('Home')}
            accessibilityLabel="Monitor at home with guidance"
            accessibilityRole="button"
          >
            <Text style={styles.btnSecondaryText}>Monitor at home with guidance</Text>
          </TouchableOpacity>
        )}

        <TouchableOpacity
          style={styles.expandToggle}
          onPress={() => setExpanded(!expanded)}
          accessibilityRole="button"
        >
          <Text style={styles.expandText}>
            {expanded ? '▲ Hide' : '▼ How was this result generated?'}
          </Text>
        </TouchableOpacity>

        {expanded && (
          <View style={styles.moduleCard}>
            <ModuleRow
              label="Symptom analysis"
              value={module_outputs.symptom?.condition_category}
              confidence={module_outputs.symptom?.confidence}
            />
            <ModuleRow
              label="Image analysis"
              value={module_outputs.image?.condition_label || 'Not assessed'}
              confidence={module_outputs.image?.confidence}
            />
            <ModuleRow
              label="Breed risk check"
              value={
                module_outputs.breed?.risk_flags?.length
                  ? module_outputs.breed.risk_flags.join(', ')
                  : 'No breed-specific risks flagged'
              }
              confidence={module_outputs.breed?.risk_flags?.length ? 1.0 : null}
            />
            <ModuleRow
              label="Urgency assessment"
              value={urgency_tier}
              confidence={confidence_score}
            />
          </View>
        )}

        <Text style={styles.disclaimer}>
          This result is generated by an Artificial Intelligence model and does not constitute a medical
          diagnosis. Always consult a qualified veterinarian for treatment decisions.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

function ModuleRow({ label, value, confidence }) {
  return (
    <View style={moduleStyles.row}>
      <Text style={moduleStyles.label}>{label}</Text>
      <Text style={moduleStyles.value}>{value || '—'}</Text>
      {confidence != null && (
        <Text style={moduleStyles.confidence}>
          {Math.round(confidence * 100)}% confidence
        </Text>
      )}
    </View>
  );
}

const moduleStyles = StyleSheet.create({
  row: { marginBottom: 12, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  label: { fontSize: 12, color: COLORS.textMuted, marginBottom: 2 },
  value: { fontSize: 14, fontWeight: '500', color: COLORS.text },
  confidence: { fontSize: 12, color: COLORS.primary, marginTop: 2 },
});

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  container: { padding: 20 },
  card: { backgroundColor: COLORS.surface, borderRadius: 10, padding: 16,
    borderWidth: 1, borderColor: COLORS.border, marginBottom: 12 },
  cardTitle: { fontSize: 13, fontWeight: '600', color: COLORS.textMuted,
    marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 },
  cardBody: { fontSize: 15, color: COLORS.text, lineHeight: 22 },
  btnPrimary: { backgroundColor: COLORS.primary, padding: 16, borderRadius: 10,
    alignItems: 'center', minHeight: 52, marginBottom: 10 },
  btnPrimaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
  btnSecondary: { borderWidth: 1, borderColor: COLORS.primary, borderRadius: 10,
    padding: 16, alignItems: 'center', minHeight: 52, marginBottom: 10 },
  btnSecondaryText: { color: COLORS.primary, fontSize: 16, fontWeight: '600' },
  expandToggle: { padding: 12, alignItems: 'center', marginBottom: 8 },
  expandText: { color: COLORS.primary, fontSize: 14 },
  moduleCard: { backgroundColor: COLORS.surface, borderRadius: 10, padding: 16,
    borderWidth: 1, borderColor: COLORS.border, marginBottom: 16 },
  disclaimer: { fontSize: 11, color: COLORS.textMuted, textAlign: 'center',
    lineHeight: 16, marginTop: 8, fontStyle: 'italic' },
});
